# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from module.remote import alpamayo_inference_pb2 as module_dot_remote_dot_alpamayo__inference__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in module/remote/alpamayo_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlpamayoInferenceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModelInfo = channel.unary_unary(
                '/carlamayo.v1.AlpamayoInference/GetModelInfo',
                request_serializer=module_dot_remote_dot_alpamayo__inference__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=module_dot_remote_dot_alpamayo__inference__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/carlamayo.v1.AlpamayoInference/Predict',
                request_serializer=module_dot_remote_dot_alpamayo__inference__pb2.PredictRequest.SerializeToString,
                response_deserializer=module_dot_remote_dot_alpamayo__inference__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.AnswerQuestion = channel.unary_unary(
                '/carlamayo.v1.AlpamayoInference/AnswerQuestion',
                request_serializer=module_dot_remote_dot_alpamayo__inference__pb2.VqaRequest.SerializeToString,
                response_deserializer=module_dot_remote_dot_alpamayo__inference__pb2.VqaResponse.FromString,
                _registered_method=True)


class AlpamayoInferenceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetModelInfo(self, request, context):
        """Handshake: which model is loaded, its camera rig and capabilities, and the
        config values the client must match (frames, history, image size).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Trajectory inference (normal / navigation / navigation+CFG).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnswerQuestion(self, request, context):
        """Visual question answering (text only, no trajectory).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlpamayoInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=module_dot_remote_dot_alpamayo__inference__pb2.GetModelInfoRequest.FromString,
                    response_serializer=module_dot_remote_dot_alpamayo__inference__pb2.ModelInfo.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=module_dot_remote_dot_alpamayo__inference__pb2.PredictRequest.FromString,
                    response_serializer=module_dot_remote_dot_alpamayo__inference__pb2.PredictResponse.SerializeToString,
            ),
            'AnswerQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AnswerQuestion,
                    request_deserializer=module_dot_remote_dot_alpamayo__inference__pb2.VqaRequest.FromString,
                    response_serializer=module_dot_remote_dot_alpamayo__inference__pb2.VqaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carlamayo.v1.AlpamayoInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('carlamayo.v1.AlpamayoInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlpamayoInference:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carlamayo.v1.AlpamayoInference/GetModelInfo',
            module_dot_remote_dot_alpamayo__inference__pb2.GetModelInfoRequest.SerializeToString,
            module_dot_remote_dot_alpamayo__inference__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carlamayo.v1.AlpamayoInference/Predict',
            module_dot_remote_dot_alpamayo__inference__pb2.PredictRequest.SerializeToString,
            module_dot_remote_dot_alpamayo__inference__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnswerQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carlamayo.v1.AlpamayoInference/AnswerQuestion',
            module_dot_remote_dot_alpamayo__inference__pb2.VqaRequest.SerializeToString,
            module_dot_remote_dot_alpamayo__inference__pb2.VqaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
